version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: basic_postgres_connection

    environment:
      POSTGRES_USER: ritankarsaha
      POSTGRES_PASSWORD: ritankar123@@
      POSTGRES_DB: golang_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
